/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 cart.gltf --transform 
Files: cart.gltf [18.35KB] > cart-transformed.glb [11.25KB] (39%)
Author: AdrianXY (https://sketchfab.com/adrianxy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-b96f896453b240ae804d0399f1faf027
Title: Shopping Cart
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cart-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        scale={3}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Griff}
        scale={3}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Chrome}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload("/cart-transformed.glb");
