/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 spotify.gltf --transform 
Files: spotify.gltf [642.15KB] > spotify-transformed.glb [320.14KB] (50%)
Author: no_na (https://sketchfab.com/no_na)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotify-icon-97ff2bf93f904e19b92a93eb23600b4a
Title: spotify icon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/spotify-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        position={[0, 0, -0.767]}
        scale={[2.714, 2.714, 0.405]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.002"]}
        position={[0.031, -0.077, -0.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.876, 0.371, 1.876]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.003"]}
        position={[-1.181, 0.54, 0.211]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.168, 0.198, 0.198]}
      />
    </group>
  );
}

useGLTF.preload("/spotify-transformed.glb");
